"""Convert Playwright Python code to Robot Framework Browser library syntax."""

import re
from typing import List, Dict, Tuple, Optional


class PlaywrightToRobotConverter:
    """Converts Playwright Python code to Robot Framework test cases."""

    def __init__(self):
        """Initialize the converter with keyword mappings."""
        self.indent = "    "
        self.action_mappings = {
            "goto": self._convert_goto,
            "click": self._convert_click,
            "fill": self._convert_fill,
            "press": self._convert_press,
            "select_option": self._convert_select_option,
            "check": self._convert_check,
            "uncheck": self._convert_uncheck,
            "hover": self._convert_hover,
            "dblclick": self._convert_dblclick,
            "get_by_role": self._convert_locator,
            "get_by_text": self._convert_locator,
            "get_by_label": self._convert_locator,
            "get_by_placeholder": self._convert_locator,
            "get_by_test_id": self._convert_locator,
            "locator": self._convert_locator,
            "wait_for_load_state": self._convert_wait_for_load_state,
            "screenshot": self._convert_screenshot,
        }

    def convert(
        self,
        playwright_code: str,
        test_name: str = "Recorded Test",
        suite_name: str = "Recorded Test Suite",
        browser: str = "chromium",
        headless: bool = False,
    ) -> str:
        """Convert Playwright code to Robot Framework test.

        Args:
            playwright_code: Python code generated by Playwright codegen
            test_name: Name for the test case
            suite_name: Name for the test suite
            browser: Browser type (chromium, firefox, webkit)
            headless: Whether to run in headless mode

        Returns:
            Robot Framework test case as a string
        """
        actions = self._parse_playwright_code(playwright_code)
        robot_test = self._generate_robot_test(
            actions=actions,
            test_name=test_name,
            suite_name=suite_name,
            browser=browser,
            headless=headless,
        )
        return robot_test

    def _parse_playwright_code(self, code: str) -> List[Dict]:
        """Parse Playwright Python code and extract actions.

        Args:
            code: Playwright Python code

        Returns:
            List of action dictionaries
        """
        actions = []
        lines = code.split("\n")

        for line in lines:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("import"):
                continue

            if "page.goto(" in line:
                url = self._extract_string_arg(line)
                if url:
                    actions.append({"type": "goto", "url": url})

            elif ".click(" in line:
                selector = self._extract_selector(line)
                if selector:
                    actions.append({"type": "click", "selector": selector})

            elif ".fill(" in line:
                selector, value = self._extract_fill_args(line)
                if selector and value:
                    actions.append({"type": "fill", "selector": selector, "value": value})

            elif ".press(" in line:
                selector, key = self._extract_press_args(line)
                if selector and key:
                    actions.append({"type": "press", "selector": selector, "key": key})

            elif ".select_option(" in line:
                selector, value = self._extract_select_args(line)
                if selector and value:
                    actions.append({"type": "select_option", "selector": selector, "value": value})

            elif ".check(" in line:
                selector = self._extract_selector(line)
                if selector:
                    actions.append({"type": "check", "selector": selector})

            elif ".uncheck(" in line:
                selector = self._extract_selector(line)
                if selector:
                    actions.append({"type": "uncheck", "selector": selector})

            elif ".hover(" in line:
                selector = self._extract_selector(line)
                if selector:
                    actions.append({"type": "hover", "selector": selector})

            elif ".dblclick(" in line:
                selector = self._extract_selector(line)
                if selector:
                    actions.append({"type": "dblclick", "selector": selector})

            elif "screenshot(" in line:
                path = self._extract_string_arg(line, arg_name="path")
                if path:
                    actions.append({"type": "screenshot", "path": path})

            elif "wait_for_load_state(" in line:
                state = self._extract_string_arg(line) or "networkidle"
                actions.append({"type": "wait_for_load_state", "state": state})

        return actions

    def _extract_string_arg(self, line: str, arg_name: Optional[str] = None) -> Optional[str]:
        """Extract a string argument from a function call."""
        if arg_name:
            pattern = rf'{arg_name}=["\']([^"\']+)["\']'
        else:
            pattern = r'["\']([^"\']+)["\']'

        match = re.search(pattern, line)
        return match.group(1) if match else None

    def _extract_selector(self, line: str) -> Optional[str]:
        """Extract selector from a Playwright action."""
        # Patterns that handle escaped characters (\\", \\') inside strings
        patterns = [
            r'locator\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
            r'get_by_role\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
            r'get_by_text\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
            r'get_by_label\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
            r'get_by_placeholder\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
            r'get_by_test_id\(["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)',
        ]

        for pattern in patterns:
            match = re.search(pattern, line)
            if match:
                # Unescape the selector (remove backslashes before quotes)
                selector = match.group(1)
                selector = selector.replace(r'\"', '"').replace(r"\'", "'")
                return selector

        # Fallback pattern with escaped character support
        match = re.search(r'["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)', line)
        if match:
            selector = match.group(1)
            selector = selector.replace(r'\"', '"').replace(r"\'", "'")
            return selector

        return None

    def _extract_fill_args(self, line: str) -> Tuple[Optional[str], Optional[str]]:
        """Extract selector and value from fill action."""
        selector = self._extract_selector(line)
        parts = line.split(".fill(")
        if len(parts) > 1:
            # Handle escaped characters in the value
            value_match = re.search(r'["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)', parts[1])
            if value_match:
                value = value_match.group(1)
                value = value.replace(r'\"', '"').replace(r"\'", "'")
                return selector, value
        return selector, None

    def _extract_press_args(self, line: str) -> Tuple[Optional[str], Optional[str]]:
        """Extract selector and key from press action."""
        selector = self._extract_selector(line)
        parts = line.split(".press(")
        if len(parts) > 1:
            # Handle escaped characters in the key
            key_match = re.search(r'["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)', parts[1])
            if key_match:
                key = key_match.group(1)
                key = key.replace(r'\"', '"').replace(r"\'", "'")
                return selector, key
        return selector, None

    def _extract_select_args(self, line: str) -> Tuple[Optional[str], Optional[str]]:
        """Extract selector and value from select_option action."""
        selector = self._extract_selector(line)
        parts = line.split(".select_option(")
        if len(parts) > 1:
            # Handle escaped characters in the value
            value_match = re.search(r'["\']([^"\'\\]*(?:\\.[^"\'\\]*)*)["\']\)', parts[1])
            if value_match:
                value = value_match.group(1)
                value = value.replace(r'\"', '"').replace(r"\'", "'")
                return selector, value
        return selector, None

    def _simplify_selector(self, selector: str) -> str:
        """Simplify selector for Robot Framework syntax.

        Converts:
        - [data-test="value"] -> data-test=value
        - [id="value"] -> id=value
        - Other bracket selectors with quotes -> remove quotes
        """
        import re

        # Pattern for [attribute="value"] or [attribute='value']
        match = re.match(r'^\[([a-zA-Z-]+)=["\']([^"\']+)["\']\]$', selector)
        if match:
            attr, value = match.groups()
            return f"{attr}={value}"

        # Pattern for removing quotes from bracket selectors
        # e.g., [data-test="value"] -> [data-test=value]
        selector = re.sub(r'\[([a-zA-Z-]+)=["\']([^"\']+)["\']\]', r'[\1=\2]', selector)

        return selector

    def _convert_goto(self, action: Dict) -> str:
        """Convert goto action to Robot Framework."""
        url = action.get("url", "")
        return f"New Page{self.indent}{url}"

    def _convert_click(self, action: Dict) -> str:
        """Convert click action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        return f"Click{self.indent}{selector}"

    def _convert_fill(self, action: Dict) -> str:
        """Convert fill action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        value = action.get("value", "")
        return f"Type Text{self.indent}{selector}{self.indent}{value}"

    def _convert_press(self, action: Dict) -> str:
        """Convert press action to Robot Framework."""
        selector = action.get("selector", "")
        key = action.get("key", "")
        return f"Keyboard Key{self.indent}press{self.indent}{key}"

    def _convert_select_option(self, action: Dict) -> str:
        """Convert select_option to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        value = action.get("value", "")
        return f"Select Options By{self.indent}{selector}{self.indent}value{self.indent}{value}"

    def _convert_check(self, action: Dict) -> str:
        """Convert check action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        return f"Check Checkbox{self.indent}{selector}"

    def _convert_uncheck(self, action: Dict) -> str:
        """Convert uncheck action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        return f"Uncheck Checkbox{self.indent}{selector}"

    def _convert_hover(self, action: Dict) -> str:
        """Convert hover action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        return f"Hover{self.indent}{selector}"

    def _convert_dblclick(self, action: Dict) -> str:
        """Convert double-click action to Robot Framework."""
        selector = self._simplify_selector(action.get("selector", ""))
        return f"Click{self.indent}{selector}{self.indent}clickCount=2"

    def _convert_wait_for_load_state(self, action: Dict) -> str:
        """Convert wait_for_load_state to Robot Framework."""
        state = action.get("state", "networkidle")
        return f"Wait For Load State{self.indent}{state}"

    def _convert_screenshot(self, action: Dict) -> str:
        """Convert screenshot action to Robot Framework."""
        path = action.get("path", "screenshot.png")
        return f"Take Screenshot{self.indent}{path}"

    def _convert_locator(self, action: Dict) -> str:
        """Handle locator-based actions."""
        return ""

    def _generate_robot_test(
        self,
        actions: List[Dict],
        test_name: str,
        suite_name: str,
        browser: str,
        headless: bool,
    ) -> str:
        """Generate complete Robot Framework test file.

        Args:
            actions: List of parsed actions
            test_name: Test case name
            suite_name: Test suite name
            browser: Browser type
            headless: Headless mode flag

        Returns:
            Complete Robot Framework test as string
        """
        lines = [
            "*** Settings ***",
            "Library    Browser",
            "",
            "",
            "*** Test Cases ***",
            test_name,
        ]

        lines.append(f"{self.indent}New Browser{self.indent}{browser}{self.indent}headless={headless}")
        lines.append(f"{self.indent}New Context{self.indent}viewport={{'width': 1920, 'height': 1080}}")

        for action in actions:
            action_type = action.get("type")
            if action_type in self.action_mappings:
                converter = self.action_mappings[action_type]
                robot_line = converter(action)
                if robot_line:
                    lines.append(f"{self.indent}{robot_line}")

        lines.append("")
        return "\n".join(lines)
